### ISSUE TITLE
Querying the same variable twice using boolean logic or using the same operator twice fails

### ISSUE THREAD

**Issue by kethinov** [kethinov/teddy#24]
e.g.

``` html
<if section='a' or section='b'>
  <p>do something</p>
</if>
```

This fails because HTML does not permit two instances of the same attribute on an element.

Likewise:

``` html
<if sectionOne or sectionTwo or sectionThree>
  <p>do something</p>
</if>
```

Because the `or` attribute is repeated.

**Comment by kethinov** [comment]
Blocked by https://github.com/kethinov/teddy/issues/32

**Comment by Autre31415** [comment]
Indirectly Tested: https://github.com/kethinov/teddy/blob/0.4.0/test/conditionals.js#L136

**Comment by kethinov** [comment]
this is not tested directly enough

can you supply a more direct test?

**Comment by Autre31415** [comment]
Covered Here: https://github.com/kethinov/teddy/blob/0.4.0/test/conditionals.js#L161

And Here: https://github.com/kethinov/teddy/blob/0.4.0/test/conditionals.js#L166
