### ISSUE TITLE
Nested comments breaks parsing

### ISSUE THREAD

**Issue by kethinov** [kethinov/teddy#27]
Notice the below code block has two sets of nested comments. If you have that, your template won't render.

``` html
<h1>everything below is commented</h1>
{!<section>
  <nav>
    <ul>
      {!<li>one</li>!}
      <li>two</li>
      <li>three</li>
    </ul>
  </nav>
</section>!}
```

**Comment by kethinov** [comment]
Blocked by https://github.com/kethinov/teddy/issues/32

**Comment by Autre31415** [comment]
Tested: https://github.com/kethinov/teddy/blob/0.4.0/test/misc.js#L42
