### ISSUE TITLE
If Conditional Evaluates Empty Array As Undefined

### ISSUE THREAD

**Issue by Hunga1** [kethinov/teddy#44]
When Teddy parses an empty array (i.e. `var testArray = []`) in an `<if something></if>` conditional, it evaluates it as `undefined` and sets it to the name of the attribute instead.

**Comment by kethinov** [comment]
Blocked by #32

**Comment by Autre31415** [comment]
Tested: https://github.com/kethinov/teddy/blob/0.4.0/test/conditionals.js#L31
