### ISSUE TITLE
One Line ifs Misinterpret String Value Equivalency With Empty Strings

### ISSUE THREAD

**Issue by Hunga1** [kethinov/teddy#46]
Passing a model attribute of type String into Teddy and using it in a one line if conditional to test equivalence with a literal string value will evaluate to true for both its actual value and an empty string.

Example:
In Controller:

``` JavaScript
model.x = 'testing';
```

In Teddy View:

``` HTML
<select>
  <option if-x='' true='selected'>Option 1</option>    <!-- This has "selected" attribute -->
  <option if-x='testing' true='selected'>Option 2</option>    <!-- This also has "selected" attribute -->
</select>
```

**Comment by kethinov** [comment]
Blocked by #32

**Comment by Autre31415** [comment]
Tested: https://github.com/kethinov/teddy/blob/0.4.0/test/conditionals.js#L130
