### ISSUE TITLE
Feature request: Array sub in loops

### ISSUE THREAD

**Issue by alallier** [kethinov/teddy#53]
Any thoughts on supporting array sub in loops

Example:

```javascript
test = [
  {
    firstName: 'John',
    lastName: 'Smith'
  }
]
```

Right now we have to do this even with one object in the array
```html
<loop through='test' val='name'>
  <p>First Name: {name.firstName}</p>
  <p>Last Name: {name.lastName}</p>
</loop>
```

It would be nice if we could do this

```html
<p>First Name: {test[0].firstName}</p>
<p>Last Name: {test[0].lastName}</p>
```

or (if we have more than one item in the array.)

```html
<p>First Name: {test[1].firstName}</p>
<p>Last Name: {test[1].lastName}</p>
```

**Comment by kethinov** [comment]
One of teddy's design goals is to encourage a stricter separation of concerns in MVC, something that is often violated in other templating systems where those sorts of "features" are available.

Directly referencing a specific element in an array by its index number definitely seems like the sort of business logic that ought to be done in the model instead by passing the result of that expression as a named variable in the model.
