### ISSUE TITLE
Included script tag in HTML will break because of certain characters

### ISSUE THREAD

**Issue by alallier** [kethinov/teddy#54]
Crudely including a script tag in your HTML can break on certain characters

Take for example this simple example using a vanilla [roosevelt](https://github.com/kethinov/roosevelt) application

`homepage.html`

``` html
<include src='layouts/main'>
  <arg pageContent>
    <article>
      <p>{content.hello}</p>
      <p>{content.picLabel}</p>
      <p><img src='{teddyPath}' alt=''></p>
      <script>
        console.log('Hello world');

        for (var i = 0; i < 2; i++) {
          console.log('Test')
        }
      </script>
    </article>
  </arg>
</include>
```

Delievered to the browser as:

``` html
<article>
  <p>Hi! I&#39;m a variable trickling down through the MVC structure!</p> <p>Here&#39;s a silly picture of Teddy Roosevelt:</p>
  <p><img src="/images/teddy.jpg" alt=""/></p>
  <script> console.log('Hello world'); for (var i = 0; i &lt; 2; i++) { console.log('Test') } </script>
</article>
```

In the for loop the less than becomes `&lt;`, causing the JavaScript to break in the browser.

Teddy is parsing the input inside of the `script` tag.

**Comment by kethinov** [comment]
fixed here https://github.com/kethinov/teddy/commit/358fba481f782d665d205e3a668742d651246935
